name: Deploy
run-name: Deploy delivered image using terraform.

on:
  repository_dispatch:
    types: [deploy-event]
jobs:
  deploy-to-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "(TEST) :: Replace tag"
        run: sed -i -E 's/(.image = )(.*):(.*)/\1\2:${{ github.event.client_payload.message }}"/' ./main.tf
